app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', ['before' => 'sentry', 'uses' => 'HomeController@index', 'as' => 'home']);

Route::get('settings', ['uses' => 'SettingsController@index', 'as' => 'settings.index']);
Route::post('settings', ['uses' => 'SettingsController@store', 'as' => 'settings.store']);

Route::get('users/logout', ['uses' => 'UsersController@logout', 'as' => 'users.logout']);
Route::get('users/login', ['uses' => 'UsersController@login', 'as' => 'users.login']);
Route::post('users/login/', ['uses' => 'UsersController@doLogin', 'as' => 'users.doLogin']);
Route::get('users/revoke-permission', ['uses' => 'UsersController@revokePermission', 'as' => 'users.revokePermission']);
Route::get('revoke', ['uses' => 'UsersController@revokePermission', 'as' => 'users.revokePermission']);
Route::get('users/change-password', ['uses' => 'UsersController@changePassword', 'as' => 'users.changePassword']);
Route::post('users/update-password', ['uses' => 'UsersController@updatePassword', 'as' => 'users.updatePassword']);

Route::resource('users', 'UsersController');

Route::resource('types', 'TypesController');

Route::resource('units', 'UnitsController');

Route::resource('customers', 'CustomersController');

Route::get('reports/stock', ['uses' => 'ReportsController@stock', 'as' => 'reports.stock']);

Route::resource('suppliers', 'SuppliersController');

Route::get('products/search', ['uses' => 'ProductsController@search', 'as' => 'products.search', 'before' => 'sentry']);

Route::resource('products', 'ProductsController');

Route::resource('salesoutlets', 'SalesOutletsController');

Route::resource('stocks', 'StocksController');

Route::get('sales/{id}/returnitem', ['uses' => 'SalesController@returnitem', 'as' => 'sales.returnitem']);
Route::resource('sales', 'SalesController');

Route::resource('colors', 'ColorsController');

Route::get('outletdeposits/{id}/approve', ['uses' => 'OutletDepositsController@approve', 'as' => 'outletdeposits.approve']);
Route::get('outletdeposits/{id}/reject', ['uses' => 'OutletDepositsController@reject', 'as' => 'outletdeposits.reject']);
Route::resource('outletdeposits', 'OutletDepositsController');

Route::resource('distributions', 'DistributionsController');

Route::resource('vats', 'VatsController');

Route::get('stockreturns/{id}/approve', ['uses' => 'StockReturnsController@approve', 'as' => 'stockreturns.approve']);
Route::get('stockreturns/{id}/reject', ['uses' => 'StockReturnsController@reject', 'as' => 'stockreturns.reject']);
Route::get('stockreturns/{id}/return', ['uses'=>'StockReturnsController@returnStock','as' => 'stockreturns.return']);
Route::resource('stockreturns', 'StockReturnsController');

Route::resource('discounts', 'DiscountsController');

app/models/OutletDeposits.php
<?php
class OutletDeposits extends Eloquent
{
    protected $table = "outlet_deposits";

    public static $rules = [
         'outlet_id' => 'required',
         'deposit' => 'required',
         'refference' => 'required',
   ];

   public static function dropdownList()
      {
         return array('' => 'Select Sales Outlet') +SalesOutlets::orderBy('name', 'asc')->get()->lists('name', 'id');
      }
    public function outlet()
   {
      return $this->hasOne('salesoutlets', 'id','outlet_id');
   }
}

app/controllers/OutletDepositsController.php
<?php

class OutletDepositsController extends \BaseController {
   public function __construct()
         {
            $this->beforeFilter('sentry');
         }
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$outletdeposits = OutletDeposits::paginate(20);
      $index = $outletdeposits->getPerPage() * ($outletdeposits->getCurrentPage()-1) + 1;
      return View::make('outletdeposits.index', compact('outletdeposits', 'index'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
      $outlets = OutletDeposits::dropdownList();
		return View::make('outletdeposits.create',compact('outlets'));
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$validator = Validator::make(Input::all(), OutletDeposits::$rules);

      if($validator->passes()) {
         $outletdeposits = new OutletDeposits;
         $outletdeposits->outlet_id = Input::get('outlet_id');
         $outletdeposits->deposit_amt = Input::get('deposit');
         $outletdeposits->refference_no = Input::get('refference');
         $outletdeposits->save();



         return Redirect::route('outletdeposits.index')
            ->with('success', 'Amount Deposited');
      }
      else {
         return Redirect::route('outletdeposits.create')
            ->withErrors($validator)
            ->withInput(Input::all());
      }
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
   	//
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
      if(!$id)
         return Redirect::route('outletdeposits.index')
            ->with('error', 'Please Provide Outlet Deposit id');

      $deposit = OutletDeposits::find($id);

      if(empty($deposit))
         return Redirect::route('outletdeposits.index')
            ->with('error', 'Deposit not found');

      $outlets = OutletDeposits::dropdownList();
      return View::make('outletdeposits.edit', compact('deposit','outlets'));
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
   {
      $validator = Validator::make(Input::all(), OutletDeposits::$rules);

      if($validator->passes()) {
         $deposit = OutletDeposits::find($id);
         $deposit->outlet_id = Input::get('outlet_id');
         $deposit->deposit_amt = Input::get('deposit');
         $deposit->refference_no = Input::get('refference');
         $deposit->save();

         return Redirect::route('outletdeposits.index')
            ->with('success', 'Outlet Deposit updated successfully');
      }
      else {
         return Redirect::route('outletdeposits.edit', $id)
            ->withErrors($validator)
            ->withInput(Input::all());
      }
   }

   public function approve($id)
   {
      $deposit = OutletDeposits::find($id);
      $deposit->status = 'Approved';
      $deposit->save();

      $salesoutlet = SalesOutlets::find($deposit->outlet_id);
      $salesoutlet->deposit = $salesoutlet->deposit + $deposit->deposit_amt;
      $salesoutlet->save();

      return Redirect::route('outletdeposits.index')
         ->with('success', 'Deposit Amount Approved');
   }



   public function reject($id)
	{
		$deposit = OutletDeposits::find($id);
      $deposit->status = 'Reject';
      $deposit->save();

      $salesoutlet = SalesOutlets::find($deposit->outlet_id);
      $salesoutlet->deposit = $salesoutlet->deposit - $deposit->deposit_amt;
      $salesoutlet->save();

      return Redirect::route('outletdeposits.index')
         ->with('success', 'Deposit Amount Rejected');
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		if (!$id)
            return Redirect::route('outletdeposits.index')
                ->with('error', 'Please provide outlet deposits id');

        $outletdeposits = OutletDeposits::find($id);

        if (empty($outletdeposits))
            return Redirect::route('outletdeposits.index')
                ->with('error', 'Outlet deposit not found');

        OutletDeposits::destroy($id);

        return Redirect::route('outletdeposits.index')
            ->with('success', 'Outlet deposit deleted successfully');
	}


}

app/views/outletdeposits/_menu.blade.php
<div class="sub-menu pull-right">
   @if( in_array($current_route, ['outletdeposits.create', 'outletdeposits.edit']) )
   <a href="{{ route('outletdeposits.index') }}" class="btn btn-xs btn-success"><i class="fa fa-arrow-left"></i> Back To List</a>
   @endif

   @if( in_array($current_route, ['outletdeposits.index', 'outletdeposits.edit']) )
   <a href="{{ route('outletdeposits.create') }}" class="btn btn-xs btn-success"><i class="fi-page-add"></i> New Deposit</a>
   @endif

   @if( in_array($current_route, ['outletdeposits.index']) )
   <a href="#" class="btn btn-xs btn-primary filter-toggle"><i class="fi-filter"></i> Filter</a>
   @endif
</div>

app/views/outletdeposits/create.blade.php
@extends('layout')

@section('content')
   <div class="col-md-6 col-md-offset-3">
      <div class="row">
         <div class="panel panel-default">
            <div class="panel-heading">
               @include('outletdeposits._menu')
               <h3 class="panel-title"><i class="fi-page-add"></i> Create New Deposit</h3>
            </div>
            <div class="panel-body">
               {{ Form::open(['url' => route('outletdeposits.store'), 'method' => 'post', 'class' => 'form-vertical', 'autocomplete' => 'off']) }}

                  <div class="form-group {{ $errors->has('outlet_id') ? 'has-error' : '' }}">
                     {{ Form::label('outlet_id', 'Sale Outlet') }}
                     {{ Form::select('outlet_id', $outlets, '', ['class' => 'form-control']) }}
                     @if($errors->has('outlet_id'))
                     <p class="help-block">{{ $errors->first('outlet_id') }}</p>
                     @endif
                  </div>

                  <div class="form-group {{ $errors->has('deposit') ? 'has-error' : '' }}">
                     {{ Form::label('deposit', 'Deposit Amount') }}
                     <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-rupee"></i></span>
                        {{ Form::text('deposit', '', ['class' => 'form-control']) }}
                     </div>
                     @if($errors->has('deposit'))
                     <p class="help-block">{{ $errors->first('deposit') }}</p>
                     @endif
                  </div>

                  <div class="form-group {{ $errors->has('refference') ? 'has-error' : '' }}">
                     {{ Form::label('refference', 'Refference No') }}
                     {{ Form::text('refference', '', ['class' => 'form-control']) }}
                     <p class="help-block">Enter Refference No</p>

                     @if($errors->has('refference'))
                     <p class="help-block">{{ $errors->first('refference') }}</p>
                     @endif
                  </div>

                  <div class="for-group text-right">
                     {{ Form::submit('Submit', ['class' => 'btn btn-primary']) }}
                  </div>
               {{ Form::close() }}
            </div>
         </div>
      </div>
   </div>
@stop

app/views/outletdeposits/edit.blade.php
@extends('layout')

@section('content')
   <div class="col-md-6 col-md-offset-3">
      <div class="row">
         <div class="panel panel-default">
            <div class="panel-heading">
               @include('outletdeposits._menu')
               <h3 class="panel-title"><i class="fi-page-add"></i> Edit Outlet Deposit</h3>
            </div>
            <div class="panel-body">
               {{ Form::open(['url' => route('outletdeposits.update',$deposit->id), 'method' => 'put', 'class' => 'form-vertical', 'autocomplete' => 'off']) }}
                  <div class="form-group {{ $errors->has('outlet_id') ? 'has-error' : '' }}">
                     {{ Form::label('outlet_id', 'Sale Outlet') }}
                     {{ Form::select('outlet_id', $outlets, $deposit->outlet_id, ['class' => 'form-control']) }}
                     @if($errors->has('outlet_id'))
                     <p class="help-block">{{ $errors->first('outlet_id') }}</p>
                     @endif
                  </div>

                  <div class="form-group {{ $errors->has('deposit') ? 'has-error' : '' }}">
                     {{ Form::label('deposit', 'Deposit Amount') }}
                     <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-rupee"></i></span>
                        {{ Form::text('deposit',  $deposit->deposit_amt, ['class' => 'form-control']) }}
                     </div>
                     @if($errors->has('deposit'))
                     <p class="help-block">{{ $errors->first('deposit') }}</p>
                     @endif
                  </div>

                  <div class="form-group {{ $errors->has('refference') ? 'has-error' : '' }}">
                     {{ Form::label('refference', 'Refference No') }}
                     {{ Form::text('refference',  $deposit->refference_no, ['class' => 'form-control']) }}

                     @if($errors->has('refference'))
                     <p class="help-block">{{ $errors->first('refference') }}</p>
                     @endif
                  </div>


                  <div class="for-group text-right">
                     {{ Form::submit('Submit', ['class' => 'btn btn-primary']) }}
                  </div>
               {{ Form::close() }}
            </div>
         </div>
      </div>
   </div>
@stop

app/views/outletdeposits/index.blade.php
@extends('layout')

@section('content')
   <div class="col-md-12">
      <div class="row">
         <div class="panel panel-default">

            <div class="panel-heading">
               @include('outletdeposits._menu')

               <h3 class="panel-title"><i class="fi-page-multiple"></i> Outlet Amount Deposit History</h3>
            </div>

            <div class="panel-body">

               <table class="table table-condensed">
                  <thead>
                     <tr>
                        <th>#</th>
                        <th class="col-md-2">Outlet</th>
                        <th class="col-md-1">Deposit Amount</th>
                        <th class="col-md-1">Balanced Amount</th>
                        <th class="col-md-2">Refference No</th>
                        <th class="col-md-1">Date</th>
                        <th class="col-md-1">Status</th>
                        <th class="col-md-6"></th>
                     </tr>
                  </thead>
                  <tbody>
                     @foreach($outletdeposits as $key => $deposit)
                     <tr>
                        <td>{{ $index+$key }}</td>
                        <td>{{ $deposit->outlet->name }}</td>
                        <td>{{ $deposit->deposit_amt }}</td>
                        <td>{{ '---' }}</td>
                        <td>{{ $deposit->refference_no }}</td>
                        <td>{{ $deposit->updated_at }}</td>
                        <td>
                           <?php
                           if($deposit->status=='Pending')
                           {
                              echo "<span  class=\"btn btn-sm btn-warning\">Pending</span>";
                           }
                           else if($deposit->status=='Approved')
                           {
                              echo "<span  class=\"btn btn-sm btn-success\">Approved</span>";
                           }
                           else if($deposit->status=='Reject')
                           {
                              echo "<span  class=\"btn btn-sm btn-danger\">Rejected</span>";
                           }
                           ?>
                        </td>
                        <td class="actions">

                           <?php
                           if($deposit->status == 'Pending' || $deposit->status=='Reject')
                           {
                           ?>
                           <a href="{{ route('outletdeposits.approve', $deposit->id ) }}" class="btn btn-sm btn-success"><i class="fi-pencil"></i> Approved</a>
                           <?php
                           }
                           if($deposit->status == 'Pending' || $deposit->status=='Approved')
                           {
                           ?>
                           <a href="{{ route('outletdeposits.reject', $deposit->id ) }}" class="btn btn-sm btn-warning"><i class="fi-pencil"></i> Reject</a>
                           <?php
                           }
                           if($deposit->status == 'Pending')
                           {
                           ?>
                           <a href="{{ route('outletdeposits.edit', $deposit->id) }}" class="btn btn-sm btn-primary"><i class="fi-pencil"></i> Edit</a>
                           <?php
                           }
                           ?>

                           {{ Form::open(['url' => route('outletdeposits.destroy', $deposit->id), 'method' => 'delete']) }}
                              {{ Form::button('<i class="fi-trash"></i> Delete', ['class' => 'btn btn-sm btn-danger', 'type' => 'submit', 'onclick' => 'return confirm("Are you sure you want to delete?")']) }}
                           {{ Form::close() }}
                        </td>
                     </tr>
                     @endforeach
                  </tbody>
               </table>

               {{ $outletdeposits->links() }}
            </div>
         </div>
      </div>
   </div>
@stop