app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', ['before' => 'sentry', 'uses' => 'HomeController@index', 'as' => 'home']);

Route::get('settings', ['uses' => 'SettingsController@index', 'as' => 'settings.index']);
Route::post('settings', ['uses' => 'SettingsController@store', 'as' => 'settings.store']);

Route::get('users/logout', ['uses' => 'UsersController@logout', 'as' => 'users.logout']);
Route::get('users/login', ['uses' => 'UsersController@login', 'as' => 'users.login']);
Route::post('users/login/', ['uses' => 'UsersController@doLogin', 'as' => 'users.doLogin']);
Route::get('users/revoke-permission', ['uses' => 'UsersController@revokePermission', 'as' => 'users.revokePermission']);
Route::get('revoke', ['uses' => 'UsersController@revokePermission', 'as' => 'users.revokePermission']);
Route::get('users/change-password', ['uses' => 'UsersController@changePassword', 'as' => 'users.changePassword']);
Route::post('users/update-password', ['uses' => 'UsersController@updatePassword', 'as' => 'users.updatePassword']);

Route::resource('users', 'UsersController');

Route::resource('types', 'TypesController');

Route::resource('units', 'UnitsController');

Route::resource('customers', 'CustomersController');

Route::get('reports/stock', ['uses' => 'ReportsController@stock', 'as' => 'reports.stock']);

Route::resource('suppliers', 'SuppliersController');

Route::get('products/search', ['uses' => 'ProductsController@search', 'as' => 'products.search', 'before' => 'sentry']);

Route::resource('products', 'ProductsController');

Route::resource('salesoutlets', 'SalesOutletsController');

Route::resource('stocks', 'StocksController');

Route::get('sales/{id}/returnitem', ['uses' => 'SalesController@returnitem', 'as' => 'sales.returnitem']);
Route::resource('sales', 'SalesController');

Route::resource('colors', 'ColorsController');

Route::get('outletdeposits/{id}/approve', ['uses' => 'OutletDepositsController@approve', 'as' => 'outletdeposits.approve']);
Route::get('outletdeposits/{id}/reject', ['uses' => 'OutletDepositsController@reject', 'as' => 'outletdeposits.reject']);
Route::resource('outletdeposits', 'OutletDepositsController');

Route::resource('distributions', 'DistributionsController');

Route::resource('vats', 'VatsController');

Route::get('stockreturns/{id}/approve', ['uses' => 'StockReturnsController@approve', 'as' => 'stockreturns.approve']);
Route::get('stockreturns/{id}/reject', ['uses' => 'StockReturnsController@reject', 'as' => 'stockreturns.reject']);
Route::get('stockreturns/{id}/return', ['uses'=>'StockReturnsController@returnStock','as' => 'stockreturns.return']);
Route::resource('stockreturns', 'StockReturnsController');

Route::resource('discounts', 'DiscountsController');

app/controllers/TypesController.php
<?php

class TypesController extends \BaseController {

   public function __construct()
   {
      $this->beforeFilter('sentry');
   }

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
      $types = Types::paginate(20);
      $index = $types->getPerPage() * ($types->getCurrentPage()-1) + 1;
		return View::make('types.index', compact('types', 'index'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('types.create');
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$validator = Validator::make(Input::all(), Types::$rules);

      if($validator->passes()) {
         $type = new Types;
         $type->name = Input::get('name');
         $type->save();

         return Redirect::route('types.index')
            ->with('success', 'Type created successfully');
      }
      else {
         return Redirect::route('types.create')
            ->withErrors($validator)
            ->withInput(Input::all());
      }
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
      if(!$id)
         return Redirect::route('types.index')
            ->with('error', 'Please provide type id');

      $type = Types::find($id);

      if(empty($type))
         return Redirect::route('types.index')
            ->with('error', 'Type not found');

		return View::make('types.edit', compact('type'));
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$validator = Validator::make(Input::all(), Types::$rules);

      if($validator->passes()) {
         $type = Types::find($id);
         $type->name = Input::get('name');
         $type->save();

         return Redirect::route('types.index')
            ->with('success', 'Type updated successfully');
      }
      else {
         return Redirect::route('types.edit', $id)
            ->withErrors($validator)
            ->withInput(Input::all());
      }
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		if(!$id)
         return Redirect::route('types.index')
            ->with('error', 'Please provide type id');

      $type = Types::find($id);

      if(empty($type))
         return Redirect::route('types.index')
            ->with('error', 'Type not found');

      Types::destroy($id);

      return Redirect::route('types.index')
         ->with('success', 'Type deleted successfully');
	}


}

app/views/types/_menu.blade.php
<div class="sub-menu pull-right">
   @if( in_array($current_route, ['types.create', 'types.edit']) )
   <a href="{{ route('types.index') }}" class="btn btn-xs btn-success"><i class="fa fa-arrow-left"></i> Back To List</a>
   @endif

   @if( in_array($current_route, ['types.index', 'types.edit']) )
   <a href="{{ route('types.create') }}" class="btn btn-xs btn-success"><i class="fi-page-add"></i> New</a>
   @endif
</div>

app/views/types/create.blade.php
@extends('layout')

@section('content')
   <div class="col-md-6 col-md-offset-3">
      <div class="row">
         <div class="panel panel-default">

            <div class="panel-heading">
               @include('types._menu')

               <h3 class="panel-title"><i class="fi-page-add"></i> Create Type</h3>
            </div>

            <div class="panel-body">
               {{ Form::open(['url' => route('types.store'), 'method' => 'post', 'class' => 'form-vertical', 'autocomplete' => 'off']) }}
                  <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                     {{ Form::label('name', 'Type Name') }}
                     {{ Form::text('name', '', ['class' => 'form-control']) }}
                     <p class="help-block">Enter type name here</p>

                     @if($errors->has('name'))
                     <p class="help-block">{{ $errors->first('name') }}</p>
                     @endif
                  </div>

                  <div class="for-group text-right">
                     {{ Form::submit('Submit', ['class' => 'btn btn-primary']) }}
                  </div>
               {{ Form::close() }}
            </div>
         </div>
      </div>
   </div>
@stop

app/views/types/edit.blade.php
@extends('layout')

@section('content')
   <div class="col-md-6 col-md-offset-3">
      <div class="row">
         <div class="panel panel-default">

            <div class="panel-heading">
               @include('types._menu')

               <h3 class="panel-title"><i class="fi-page-edit"></i> Edit Type</h3>
            </div>

            <div class="panel-body">
               {{ Form::open(['url' => route('types.update', $type->id), 'method' => 'put', 'class' => 'form-vertical', 'autocomplete' => 'off']) }}
                  <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                     {{ Form::label('name', 'Type Name') }}
                     {{ Form::text('name', $type->name, ['class' => 'form-control']) }}
                     <p class="help-block">Enter type name here</p>

                     @if($errors->has('name'))
                     <p class="help-block">{{ $errors->first('name') }}</p>
                     @endif
                  </div>

                  <div class="for-group text-right">
                     {{ Form::submit('Save', ['class' => 'btn btn-primary']) }}
                  </div>
               {{ Form::close() }}
            </div>
         </div>
      </div>
   </div>
@stop

app/views/types/index.blade.php
@extends('layout')

@section('content')
   <div class="col-md-6 col-md-offset-3">
      <div class="row">
         <div class="panel panel-default">

            <div class="panel-heading">
               @include('types._menu')

               <h3 class="panel-title"><i class="fi-page-multiple"></i> Types</h3>
            </div>

            <div class="panel-body">
               <table class="table table-condensed">
                  <thead>
                     <tr>
                        <th>#</th>
                        <th class="col-md-6">Type Name</th>
                        <th class="col-md-6"></th>
                     </tr>
                  </thead>
                  <tbody>
                     @foreach($types as $key => $type)
                     <tr>
                        <td>{{ $index+$key }}</td>
                        <td>{{ $type->name }}</td>
                        <td class="actions">
                           <a href="{{ route('types.edit', $type->id) }}" class="btn btn-sm btn-primary"><i class="fi-pencil"></i> Edit</a>
                           {{ Form::open(['url' => route('types.destroy', $type->id), 'method' => 'delete']) }}
                              {{ Form::button('<i class="fi-trash"></i> Delete', ['class' => 'btn btn-sm btn-danger', 'type' => 'submit', 'onclick' => 'return confirm("Are you sure you want to delete?")']) }}
                           {{ Form::close() }}
                        </td>
                     </tr>
                     @endforeach
                  </tbody>
               </table>

               {{ $types->links() }}
            </div>
         </div>
      </div>
   </div>
@stop