app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', ['before' => 'sentry', 'uses' => 'HomeController@index', 'as' => 'home']);

Route::get('settings', ['uses' => 'SettingsController@index', 'as' => 'settings.index']);
Route::post('settings', ['uses' => 'SettingsController@store', 'as' => 'settings.store']);

Route::get('users/logout', ['uses' => 'UsersController@logout', 'as' => 'users.logout']);
Route::get('users/login', ['uses' => 'UsersController@login', 'as' => 'users.login']);
Route::post('users/login/', ['uses' => 'UsersController@doLogin', 'as' => 'users.doLogin']);
Route::get('users/revoke-permission', ['uses' => 'UsersController@revokePermission', 'as' => 'users.revokePermission']);
Route::get('revoke', ['uses' => 'UsersController@revokePermission', 'as' => 'users.revokePermission']);
Route::get('users/change-password', ['uses' => 'UsersController@changePassword', 'as' => 'users.changePassword']);
Route::post('users/update-password', ['uses' => 'UsersController@updatePassword', 'as' => 'users.updatePassword']);

Route::resource('users', 'UsersController');

Route::resource('types', 'TypesController');

Route::resource('units', 'UnitsController');

Route::resource('customers', 'CustomersController');

Route::get('reports/stock', ['uses' => 'ReportsController@stock', 'as' => 'reports.stock']);

Route::resource('suppliers', 'SuppliersController');

Route::get('products/search', ['uses' => 'ProductsController@search', 'as' => 'products.search', 'before' => 'sentry']);

Route::resource('products', 'ProductsController');

Route::resource('salesoutlets', 'SalesOutletsController');

Route::resource('stocks', 'StocksController');

Route::get('sales/{id}/returnitem', ['uses' => 'SalesController@returnitem', 'as' => 'sales.returnitem']);
Route::resource('sales', 'SalesController');

Route::resource('colors', 'ColorsController');

Route::get('outletdeposits/{id}/approve', ['uses' => 'OutletDepositsController@approve', 'as' => 'outletdeposits.approve']);
Route::get('outletdeposits/{id}/reject', ['uses' => 'OutletDepositsController@reject', 'as' => 'outletdeposits.reject']);
Route::resource('outletdeposits', 'OutletDepositsController');

Route::resource('distributions', 'DistributionsController');

Route::resource('vats', 'VatsController');

Route::get('stockreturns/{id}/approve', ['uses' => 'StockReturnsController@approve', 'as' => 'stockreturns.approve']);
Route::get('stockreturns/{id}/reject', ['uses' => 'StockReturnsController@reject', 'as' => 'stockreturns.reject']);
Route::get('stockreturns/{id}/return', ['uses'=>'StockReturnsController@returnStock','as' => 'stockreturns.return']);
Route::resource('stockreturns', 'StockReturnsController');

Route::resource('discounts', 'DiscountsController');

app/models/SalesOutlets.php
<?php
class SalesOutlets extends Eloquent
{
	protected $table = "sales_outlets";
   public static $rules = [
         'name' => 'required',
         'address' => 'required'
   ];

   public static function dropdownList($select = false)
   {
   		if($select)
      		return array('0' => 'Select Outlet') + self::orderBy('name', 'asc')->get()->lists('name', 'id');
      	else
      		return array('all' => 'All Outlets') + self::orderBy('name', 'asc')->get()->lists('name', 'id');
   }
}

app/controllers/SalesOutletsController.php
<?php

class SalesOutletsController extends \BaseController {
   public function __construct()
      {
         $this->beforeFilter('sentry');
      }
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$salesoutlets = SalesOutlets::paginate(20);
      $index = $salesoutlets->getPerPage() * ($salesoutlets->getCurrentPage()-1) + 1;
      return View::make('salesoutlets.index', compact('salesoutlets', 'index'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('salesoutlets.create');
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$validator = Validator::make(Input::all(), SalesOutlets::$rules);

      if($validator->passes()) {
         $salesoutlet = new SalesOutlets;
         $salesoutlet->name = Input::get('name');
         $salesoutlet->address = Input::get('address');
         $salesoutlet->contact= Input::get('contact');
         $salesoutlet->save();

         return Redirect::route('salesoutlets.index')
            ->with('success', 'Sales Outlet Created Successfully');
      }
      else {
         return Redirect::route('salesoutlets.create')
            ->withErrors($validator)
            ->withInput(Input::all());
      }
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		if(!$id)
         return Redirect::route('salesoutlets.index')
            ->with('error', 'Please provide Sales Outlet id');

      $salesoutlet = SalesOutlets::find($id);

      if(empty($salesoutlet))
         return Redirect::route('salesoutlets.index')
            ->with('error', 'Sales Outlet not found');

      return View::make('salesoutlets.edit', compact('salesoutlet'));
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$validator = Validator::make(Input::all(), SalesOutlets::$rules);

      if($validator->passes()) {
         $salesoutlet = SalesOutlets::find($id);
         $salesoutlet->name = Input::get('name');
         $salesoutlet->address = Input::get('address');
         $salesoutlet->contact = Input::get('contact');
         $salesoutlet->save();

         return Redirect::route('salesoutlets.index')
            ->with('success', 'Sales Outlet updated successfully');
      }
      else {
         return Redirect::route('salesoutlets.edit', $id)
            ->withErrors($validator)
            ->withInput(Input::all());
      }
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		if(!$id)
         return Redirect::route('salesoutlets.index')
            ->with('error', 'Please provide Sales Outlet id');

      $salesoutlet = SalesOutlets::find($id);

      if(empty($salesoutlet))
         return Redirect::route('salesoutlets.index')
            ->with('error', 'Sales Outlet not found');

      Salesoutlets::destroy($id);

      return Redirect::route('salesoutlets.index')
         ->with('success', 'Sales Outlet deleted successfully');
	}


}

app/views/salesoutlets/_menu.blade.php
<div class="sub-menu pull-right">
   @if( in_array($current_route, ['salesoutlets.create', 'salesoutlets.edit']) )
   <a href="{{ route('salesoutlets.index') }}" class="btn btn-xs btn-success"><i class="fa fa-arrow-left"></i> Back To List</a>
   @endif

   @if( in_array($current_route, ['salesoutlets.index', 'salesoutlets.edit']) )
   <a href="{{ route('salesoutlets.create') }}" class="btn btn-xs btn-success"><i class="fi-page-add"></i> New</a>
   @endif
</div>

app/views/salesoutlets/create.blade.php
@extends('layout')

@section('content')
   <div class="col-md-6 col-md-offset-3">
      <div class="row">
         <div class="panel panel-default">
            <div class="panel-heading">
               @include('salesoutlets._menu')
               <h3 class="panel-title"><i class="fi-page-add"></i> Create Sales Outlet</h3>
            </div>
            <div class="panel-body">
               {{ Form::open(['url' => route('salesoutlets.store'), 'method' => 'post', 'class' => 'form-vertical', 'autocomplete' => 'off']) }}
                  <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                     {{ Form::label('name', 'Sales Outlet Name') }}
                     {{ Form::text('name', '', ['class' => 'form-control']) }}
                     @if($errors->has('name'))
                     <p class="help-block">{{ $errors->first('name') }}</p>
                     @endif
                  </div>

                  <div class="form-group {{ $errors->has('address') ? 'has-error' : '' }}">
                     {{ Form::label('address', 'Address') }}
                     {{ Form::text('address', '', ['class' => 'form-control']) }}
                     @if($errors->has('address'))
                     <p class="help-block">{{ $errors->first('address') }}</p>
                     @endif
                  </div>

                  <div class="form-group {{ $errors->has('contact') ? 'has-error' : '' }}">
                     {{ Form::label('contact', 'Contact') }}
                     {{ Form::text('contact', '', ['class' => 'form-control']) }}
                     @if($errors->has('contact'))
                     <p class="help-block">{{ $errors->first('contact') }}</p>
                     @endif
                  </div>

                  <div class="for-group text-right">
                     {{ Form::submit('Submit', ['class' => 'btn btn-primary']) }}
                  </div>
               {{ Form::close() }}
            </div>
         </div>
      </div>
   </div>
@stop

app/views/salesoutlets/edit.blade.php
@extends('layout')

@section('content')
   <div class="col-md-6 col-md-offset-3">
      <div class="row">
         <div class="panel panel-default">

            <div class="panel-heading">
               @include('salesoutlets._menu')

               <h3 class="panel-title"><i class="fi-page-edit"></i> Edit Sales Outlet</h3>
            </div>

            <div class="panel-body">
               {{ Form::open(['url' => route('salesoutlets.update', $salesoutlet->id), 'method' => 'put', 'class' => 'form-vertical', 'autocomplete' => 'off']) }}
                  <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                     {{ Form::label('name', 'salesoutlet Name') }}
                     {{ Form::text('name', $salesoutlet->name, ['class' => 'form-control']) }}
                     @if($errors->has('name'))
                     <p class="help-block">{{ $errors->first('name') }}</p>
                     @endif
                  </div>

                  <div class="form-group {{ $errors->has('address') ? 'has-error' : '' }}">
                     {{ Form::label('address', 'Address') }}
                     {{ Form::text('address', $salesoutlet->address, ['class' => 'form-control']) }}
                     @if($errors->has('address'))
                     <p class="help-block">{{ $errors->first('address') }}</p>
                     @endif
                  </div>

                  <div class="form-group {{ $errors->has('contact') ? 'has-error' : '' }}">
                     {{ Form::label('contact', 'Contact') }}
                     {{ Form::text('contact', $salesoutlet->contact, ['class' => 'form-control']) }}

                     @if($errors->has('contact'))
                     <p class="help-block">{{ $errors->first('contact') }}</p>
                     @endif
                  </div>

                  <div class="for-group text-right">
                     {{ Form::submit('Save', ['class' => 'btn btn-primary']) }}
                  </div>
               {{ Form::close() }}
            </div>
         </div>
      </div>
   </div>
@stop

app/views/salesoutlets/index.blade.php
@extends('layout')

@section('content')
   <div class="col-md-12">
      <div class="row">
         <div class="panel panel-default">
            <div class="panel-heading">
               @include('salesoutlets._menu')
               <h3 class="panel-title"><i class="fi-page-multiple"></i> Sales Outlets</h3>
            </div>
            <div class="panel-body">
               <table class="table table-condensed">
                  <thead>
                     <tr>
                        <th>#</th>
                        <th class="col-md-3">Sale Outlet</th>
                        <th class="col-md-3">Address</th>
                        <th class="col-md-3">Contact</th>
                        <th class="col-md-3"></th>
                     </tr>
                  </thead>
                  <tbody>
                     @foreach($salesoutlets as $key => $salesoutlet)
                     <tr>
                        <td>{{ $index+$key }}</td>
                        <td>{{ $salesoutlet->name }}</td>
                        <td>{{ $salesoutlet->address }}</td>
                        <td>{{ $salesoutlet->contact }}</td>
                        <td class="actions">
                           <a href="{{ route('salesoutlets.edit', $salesoutlet->id) }}" class="btn btn-sm btn-primary"><i class="fi-pencil"></i> Edit</a>
                           {{ Form::open(['url' => route('salesoutlets.destroy', $salesoutlet->id), 'method' => 'delete']) }}
                              {{ Form::button('<i class="fi-trash"></i> Delete', ['class' => 'btn btn-sm btn-danger', 'type' => 'submit', 'onclick' => 'return confirm("Are you sure you want to delete?")']) }}
                           {{ Form::close() }}
                        </td>
                     </tr>
                     @endforeach
                  </tbody>
               </table>

               {{ $salesoutlets->links() }}
            </div>
         </div>
      </div>
   </div>
@stop